name: allureHistoryWithStaticPage

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install
          yarn playwright install chromium

      - name: Install Allure Command-Line Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget -q https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.tgz
          tar -xzf allure-2.17.3.tgz
          sudo mv allure-2.17.3 /opt/allure
          echo 'export PATH=$PATH:/opt/allure/bin' >> $GITHUB_ENV
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: yarn run test
        continue-on-error: true

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Clone gh-pages Branch
        run: |
          git clone --branch=gh-pages "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git" gh-pages
          mkdir -p gh-pages/reports

      - name: Compile and Run TypeScript Script
   
